# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

amd64:
  - name: k8s
    install-type: store
    classic: true
    revision: 4539
arm64:
  - name: k8s
    install-type: store
    classic: true
    revision: 4540
