# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

amd64:
- classic: true
  install-type: store
  name: k8s
  revision: 4708
arm64:
- classic: true
  install-type: store
  name: k8s
  revision: 4698
